spring:
  application:
    name: ecom-eureka-server
  boot:
    admin:
      context-path: /admin
server:
  port: 8761
eureka:
  instance:
    hostname: ${VM_IP:127.0.0.1}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5


management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4317
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans   

